# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: cd src/main && bash ../../build-release.sh
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1
        name: Release v1
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          ./src/main/lanproxy-client-darwin-amd64-1.tar.gz
          ./src/main/lanproxy-client-freebsd-amd64-1.tar.gz
          ./src/main/lanproxy-client-linux-amd64-1.tar.gz
          ./src/main/lanproxy-client-windows-amd64-1.tar.gz
          ./src/main/lanproxy-client-linux-arm-1.tar.gz
          ./src/main/lanproxy-client-linux-mips-1.tar.gz
          ./src/main/lanproxy-client-linux-mipsle-1.tar.gz
